# This file is responsible for configuring your application
# and its dependencies with the aid of the Config module.
#
# This configuration file is loaded before any dependency and
# is restricted to this project.

# General application configuration
import Config

config :wordle_clone,
  ecto_repos: [WordleClone.Repo]

# Configures the endpoint
config :wordle_clone, WordleCloneWeb.Endpoint,
  url: [host: "localhost"],
  render_errors: [view: WordleCloneWeb.ErrorView, accepts: ~w(html json), layout: false],
  pubsub_server: WordleClone.PubSub,
  live_view: [signing_salt: "bfZLMvST"]

# Configures the mailer
#
# By default it uses the "Local" adapter which stores the emails
# locally. You can see the emails in your browser, at "/dev/mailbox".
#
# For production it's recommended to configure a different adapter
# at the `config/runtime.exs`.
config :wordle_clone, WordleClone.Mailer, adapter: Swoosh.Adapters.Local

# Configure esbuild (the version is required)
config :esbuild,
  version: "0.14.29",
  default: [
    args:
      ~w(js/app.js --bundle --target=es2017 --outdir=../priv/static/assets --external:/fonts/* --external:/images/*),
    cd: Path.expand("../assets", __DIR__),
    env: %{"NODE_PATH" => Path.expand("../deps", __DIR__)}
  ]

config :tailwind,
  version: "3.3.2",
  default: [
    args: ~w(
      --config=tailwind.config.js
      --input=css/app.css
      --output=../priv/static/assets/app.css
    ),
    cd: Path.expand("../assets", __DIR__)
  ]

# Configures Elixir's Logger
config :logger, :console,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id],
  level: :info

# Use Jason for JSON parsing in Phoenix
config :phoenix, :json_library, Jason

config :wordle_clone,
  game_solutions: [
    "cream",
    "exact",
    "apply",
    "above",
    "drawn",
    "grace",
    "frame",
    "start",
    "ahead",
    "drove",
    "lying",
    "front",
    "brief",
    "lucky",
    "vital",
    "video",
    "grand",
    "mixed",
    "model",
    "clean",
    "phase",
    "trust",
    "while",
    "extra",
    "carry",
    "mount",
    "basis",
    "input",
    "noise",
    "round",
    "cross",
    "nurse",
    "wrote",
    "smile",
    "enemy",
    "ocean",
    "award",
    "bench",
    "angry",
    "range",
    "angle",
    "there",
    "north",
    "leave",
    "learn",
    "along",
    "baker",
    "thank",
    "arise",
    "break",
    "slide",
    "radio",
    "bases",
    "trade",
    "other",
    "chain",
    "order",
    "raise",
    "valid",
    "ideal",
    "stock",
    "glass",
    "media",
    "aside",
    "grade",
    "being",
    "every",
    "music",
    "audit",
    "bread",
    "theme",
    "stood",
    "globe",
    "whose",
    "state",
    "aware",
    "booth",
    "bring",
    "index",
    "stake",
    "argue",
    "brain",
    "begin",
    "house",
    "calif",
    "given",
    "steam",
    "juice",
    "month",
    "badly",
    "audio",
    "eight",
    "buyer",
    "apple",
    "asset",
    "fifty",
    "still",
    "cross",
    "noted",
    "virus",
    "funny",
    "their",
    "where",
    "below",
    "coach",
    "tried",
    "force",
    "early",
    "abuse",
    "major",
    "voice",
    "grass",
    "trial",
    "china",
    "usual",
    "value",
    "young",
    "alive",
    "faith",
    "birth",
    "civil",
    "agree",
    "stone",
    "light",
    "broad",
    "boost",
    "youth",
    "march",
    "avoid",
    "dream",
    "exist",
    "cause",
    "since",
    "maker",
    "begun",
    "dozen",
    "ought",
    "chart",
    "match",
    "issue",
    "price",
    "watch",
    "blood",
    "which",
    "worry",
    "crime",
    "hotel",
    "anger",
    "earth",
    "texas",
    "heart",
    "crowd",
    "field",
    "often",
    "enter",
    "sixty",
    "drama",
    "frank",
    "treat",
    "skill",
    "urban",
    "newly",
    "would",
    "stick",
    "class",
    "never",
    "sleep",
    "apart",
    "lunch",
    "novel",
    "visit",
    "legal",
    "fraud",
    "allow",
    "false",
    "fifth",
    "basic",
    "laugh",
    "logic",
    "agent",
    "later",
    "panel",
    "catch",
    "wheel",
    "cycle",
    "blame",
    "trend",
    "arena",
    "going",
    "guide",
    "alone",
    "paper",
    "local",
    "human",
    "album",
    "guest",
    "admit",
    "alter",
    "world",
    "laser",
    "first",
    "small",
    "paint",
    "thick",
    "giant",
    "magic",
    "acute",
    "limit",
    "cause",
    "cable",
    "blind",
    "brand",
    "worst",
    "fault",
    "clear",
    "drill",
    "motor",
    "clock",
    "among",
    "needs",
    "adopt",
    "fluid",
    "layer",
    "image",
    "steel",
    "horse",
    "floor",
    "chair",
    "billy",
    "inner",
    "water",
    "beach",
    "night",
    "enjoy",
    "began",
    "great",
    "metal",
    "dress",
    "fixed",
    "these",
    "royal",
    "array",
    "elite",
    "dying",
    "irony",
    "adult",
    "sized",
    "offer",
    "click",
    "craft",
    "judge",
    "truly",
    "draft",
    "loose",
    "mouth",
    "party",
    "drive",
    "doubt",
    "large",
    "teeth",
    "again",
    "tries",
    "route",
    "black",
    "chose",
    "usage",
    "level",
    "wrong",
    "crown",
    "minus",
    "meant",
    "least",
    "fruit",
    "flash",
    "empty",
    "worse",
    "happy",
    "alike",
    "after",
    "write",
    "peace",
    "alarm",
    "movie",
    "eager",
    "alert",
    "drink",
    "chase",
    "known",
    "mayor",
    "bound",
    "minor",
    "about",
    "worth",
    "moral",
    "smith",
    "gross",
    "fully",
    "might",
    "mouse"
  ]

# Import environment specific config. This must remain at the bottom
# of this file so it overrides the configuration defined above.
import_config "#{config_env()}.exs"
